import { DM_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";
import DashboardShell from "./client";
import QueryProvider from "@/components/providers/QueryProvider";

const dmSans = DM_Sans({
  variable: "--font-sans",
  subsets: ["latin"],
});
const playFair = Playfair_Display({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "CraftBasket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${playFair.variable} antialiased bg-white w-screen`}
      >
        <QueryProvider>
          <DashboardShell>{children}</DashboardShell>
        </QueryProvider>
      </body>
    </html>
  );
}
