import { DM_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";

import QueryProvider from "@/components/providers/QueryProvider";

import PageShell from "./inner";

const dmSans = DM_Sans({
  variable: "--font-dmSans",
  subsets: ["latin"],
});
const playFair = Playfair_Display({
  variable: "--font-playFair",
  subsets: ["latin"],
});

export const metadata = {
  title: "CraftBasket",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${playFair.variable} antialiased bg-white font-sans`}
      >
        <QueryProvider>
          <PageShell>{children}</PageShell>
        </QueryProvider>
      </body>
    </html>
  );
}
