// Temporary mock orders — used as a fallback only when GET /orders returns
// nothing yet, so the orders page renders a complete UI. Remove once the
// backend reliably returns order history.
export const MOCK_ORDERS = [
  {
    id: "mock-1",
    name: "Black Embroidered Tote",
    color: "Black",
    personalization: "None",
    price: 30000,
    status: "In Progress",
    deliveryDate: "Est. 7 Jan",
    image: "/product.png",
    year: 2026,
    cancellable: true,
  },
  {
    id: "mock-2",
    name: "Scented Candle Set",
    color: "Ivory",
    personalization: "Name engraved",
    price: 18500,
    status: "Delivered",
    deliveryDate: "On 12 Aug",
    image: "/product2.png",
    year: 2025,
    cancellable: false,
  },
  {
    id: "mock-3",
    name: "Floral Dream Trio",
    color: "Pink",
    personalization: "None",
    price: 53000,
    status: "Delivered",
    deliveryDate: "On 12 Aug",
    image: "/product.png",
    year: 2025,
    cancellable: false,
  },
  {
    id: "mock-4",
    name: "Mini Gift Hamper",
    color: "Brown",
    personalization: "None",
    price: 30000,
    status: "Canceled",
    deliveryDate: "",
    image: "/product2.png",
    year: 2025,
    cancellable: false,
  },
];
